### ISSUE TITLE
Make a springboot students data list view api

### ISSUE THREAD

**Issue by sujal-garg** [Developer-Student-Clubs-MMDU/Backend-Web-Development#18]

**Comment by uk47kumar** [comment]
can you assign this to me ?

**Comment by sujalgarg17** [comment]
Yes, Sure.

**Comment by sujalgarg17** [comment]
@uk47kumar have assigned it to you make sure you follow all the contribution  guidelines

**Comment by uk47kumar** [comment]
ok, Thnx I will follow the guidelines..

**Comment by sujal-garg** [comment]
Successful contributed by @uk47kumar
